name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake -DBUILD_TESTS=1 ..
    - name: make
      run: cd build && cmake --build .
